const fs = require('fs');

function translateLogisticsData() {
  let data = fs.readFileSync('src/data/logisticsData.ts', 'utf8');

  // Add Arabic translations to OFFICE_HUBS
  data = data.replace(/city: 'Shenzhen \(Headquarters\)'/, "city: 'Shenzhen (Headquarters)', cityAr: 'شينزين (المقر الرئيسي)'");
  data = data.replace(/region: 'Guangdong Province \/ Greater Bay Area'/, "region: 'Guangdong Province / Greater Bay Area', regionAr: 'مقاطعة غوانغدونغ / منطقة الخليج الكبرى'");
  data = data.replace(/role: 'Global Logistics Command & South China Sourcing HQ'/, "role: 'Global Logistics Command & South China Sourcing HQ', roleAr: 'قيادة اللوجستيات العالمية والمقر الرئيسي للتوريد في جنوب الصين'");
  data = data.replace(/teamLead: 'Marcus Chen, Head of South China Logistics'/, "teamLead: 'Marcus Chen, Head of South China Logistics', teamLeadAr: 'ماركوس تشين، رئيس الخدمات اللوجستية في جنوب الصين'");
  data = data.replace(/specialty: 'Ocean FCL\/LCL out of Yantian & Shekou, electronics & hardware supply chains, Shenzhen-Hong Kong cross-border trucking\.'/g, "specialty: 'Ocean FCL/LCL out of Yantian & Shekou, electronics & hardware supply chains, Shenzhen-Hong Kong cross-border trucking.', specialtyAr: 'الشحن البحري من يانتيان وشيكو، سلاسل توريد الإلكترونيات والأجهزة، النقل البري عبر الحدود بين شينزين وهونغ كونغ.'");

  data = data.replace(/city: 'Hong Kong \(SAR\)'/, "city: 'Hong Kong (SAR)', cityAr: 'هونغ كونغ (منطقة إدارية خاصة)'");
  data = data.replace(/region: 'International Corporate & Financial Gateway'/, "region: 'International Corporate & Financial Gateway', regionAr: 'البوابة الدولية للشركات والتمويل'");
  data = data.replace(/role: 'Corporate Formation, Cross-Border Treasury & Air Cargo Gateway'/, "role: 'Corporate Formation, Cross-Border Treasury & Air Cargo Gateway', roleAr: 'تأسيس الشركات، الخزانة عبر الحدود وبوابة الشحن الجوي'");
  data = data.replace(/teamLead: 'Cynthia Wong, TCSP Licensed Corporate Director'/, "teamLead: 'Cynthia Wong, TCSP Licensed Corporate Director', teamLeadAr: 'سينثيا وونغ، مديرة شركات مرخصة (TCSP)'");
  data = data.replace(/specialty: 'HK Limited incorporation, multi-currency corporate banking, air freight consolidation via HKG hub\.'/g, "specialty: 'HK Limited incorporation, multi-currency corporate banking, air freight consolidation via HKG hub.', specialtyAr: 'تأسيس شركات هونغ كونغ، حسابات بنكية متعددة العملات، تجميع الشحن الجوي.'");

  data = data.replace(/city: 'Ningbo & Yiwu'/, "city: 'Ningbo & Yiwu', cityAr: 'نينغبو وإيوو'");
  data = data.replace(/region: 'Zhejiang Province \(East China Industrial Belt\)'/, "region: 'Zhejiang Province (East China Industrial Belt)', regionAr: 'مقاطعة تشجيانغ (الحزام الصناعي لشرق الصين)'");
  data = data.replace(/role: 'East China Port Logistics & Small Commodity Sourcing Hub'/, "role: 'East China Port Logistics & Small Commodity Sourcing Hub', roleAr: 'لوجستيات موانئ شرق الصين ومركز توريد السلع الصغيرة'");
  data = data.replace(/teamLead: 'Kevin Zhou, Regional Sourcing & Quality Director'/, "teamLead: 'Kevin Zhou, Regional Sourcing & Quality Director', teamLeadAr: 'كيفن تشو، المدير الإقليمي للتوريد والجودة'");
  data = data.replace(/specialty: 'Beilun sea freight dispatch, on-site Yiwu market sourcing, China-Europe freight train direct loadings\.'/g, "specialty: 'Beilun sea freight dispatch, on-site Yiwu market sourcing, China-Europe freight train direct loadings.', specialtyAr: 'إرسال الشحن البحري من بيلون، التوريد الميداني من سوق إيوو، التحميل المباشر لقطارات الشحن بين الصين وأوروبا.'");

  data = data.replace(/city: 'Shanghai'/, "city: 'Shanghai', cityAr: 'شانغهاي'");
  data = data.replace(/region: 'Yangtze River Delta Economic Hub'/, "region: 'Yangtze River Delta Economic Hub', regionAr: 'المركز الاقتصادي لدلتا نهر اليانغتسي'");
  data = data.replace(/role: 'Northern & Central China Export Logistics & WFOE Services'/, "role: 'Northern & Central China Export Logistics & WFOE Services', roleAr: 'لوجستيات التصدير في شمال ووسط الصين وخدمات WFOE'");
  data = data.replace(/teamLead: 'Elena Wang, Legal & Corporate Structuring Partner'/, "teamLead: 'Elena Wang, Legal & Corporate Structuring Partner', teamLeadAr: 'إيلينا وانغ، شريكة الهيكلة القانونية والشركات'");
  data = data.replace(/specialty: 'Yangshan port ocean freight, chemical & industrial equipment customs brokerage, China WFOE SAMR registrations\.'/g, "specialty: 'Yangshan port ocean freight, chemical & industrial equipment customs brokerage, China WFOE SAMR registrations.', specialtyAr: 'الشحن البحري من ميناء يانغشان، التخليص الجمركي للمعدات الكيميائية والصناعية، تسجيلات الشركات WFOE.'");

  // Add Arabic to FREIGHT_MODES
  data = data.replace(/name: 'Ocean FCL \(Full Container\)'/, "name: 'Ocean FCL (Full Container)', nameAr: 'الشحن البحري للحاويات الكاملة (FCL)'");
  data = data.replace(/badge: 'Cost Efficient'/, "badge: 'Cost Efficient', badgeAr: 'فعال من حيث التكلفة'");
  data = data.replace(/typicalTime: '12 - 30 Days'/, "typicalTime: '12 - 30 Days', typicalTimeAr: '12 - 30 يوماً'");
  data = data.replace(/summary: 'Direct port-to-port and door-to-door full container carriage \(20’GP, 40’GP, 40’HQ, 45’HQ, Refrigerated\). Contracts with MAERSK, MSC, COSCO, ONE, CMA CGM\.'/g, "summary: 'Direct port-to-port and door-to-door full container carriage (20’GP, 40’GP, 40’HQ, 45’HQ, Refrigerated). Contracts with MAERSK, MSC, COSCO, ONE, CMA CGM.', summaryAr: 'النقل المباشر للحاويات الكاملة من الميناء للميناء ومن الباب للباب. عقود مباشرة مع شركات الشحن العالمية.'");

  data = data.replace(/name: 'Ocean LCL \(Consolidation\)'/, "name: 'Ocean LCL (Consolidation)', nameAr: 'الشحن البحري الجزئي (LCL)'");
  data = data.replace(/badge: 'Volume Flexible'/, "badge: 'Volume Flexible', badgeAr: 'مرونة في الحجم'");
  data = data.replace(/typicalTime: '14 - 35 Days'/, "typicalTime: '14 - 35 Days', typicalTimeAr: '14 - 35 يوماً'");
  data = data.replace(/summary: 'Cost-effective consolidation for cargo from 1 CBM to 15 CBM. We combine your goods with vetted commercial cargo in our own Shenzhen\/Ningbo bonded CFS warehouses\.'/g, "summary: 'Cost-effective consolidation for cargo from 1 CBM to 15 CBM. We combine your goods with vetted commercial cargo in our own Shenzhen/Ningbo bonded CFS warehouses.', summaryAr: 'تجميع فعال من حيث التكلفة للشحنات من 1 إلى 15 متر مكعب. نقوم بتجميع بضائعك في مستودعاتنا الخاصة.'");

  data = data.replace(/name: 'Air Freight & Express'/, "name: 'Air Freight & Express', nameAr: 'الشحن الجوي السريع'");
  data = data.replace(/badge: 'Speed Critical'/, "badge: 'Speed Critical', badgeAr: 'سرعة فائقة'");
  data = data.replace(/typicalTime: '1 - 4 Days'/, "typicalTime: '1 - 4 Days', typicalTimeAr: '1 - 4 أيام'");
  data = data.replace(/summary: 'Direct charter and commercial scheduled belly space from Hong Kong \(HKG\), Shenzhen \(SZX\), Guangzhou \(CAN\), and Shanghai \(PVG\) to major worldwide airport hubs\.'/g, "summary: 'Direct charter and commercial scheduled belly space from Hong Kong (HKG), Shenzhen (SZX), Guangzhou (CAN), and Shanghai (PVG) to major worldwide airport hubs.', summaryAr: 'مساحات شحن جوي تجارية ومستأجرة مباشرة من المطارات الرئيسية في الصين وهونغ كونغ إلى المطارات العالمية.'");

  data = data.replace(/name: 'China-Europe Railway Express'/, "name: 'China-Europe Railway Express', nameAr: 'قطار الشحن السريع بين الصين وأوروبا'");
  data = data.replace(/badge: 'Eco Balance'/, "badge: 'Eco Balance', badgeAr: 'توازن بيئي'");
  data = data.replace(/typicalTime: '14 - 18 Days'/, "typicalTime: '14 - 18 Days', typicalTimeAr: '14 - 18 يوماً'");
  data = data.replace(/summary: 'The iron silk road connecting Yiwu, Xi’an, and Chongqing to Duisburg, Hamburg, Warsaw, and Madrid. 50% faster than sea freight at 60% lower cost than air freight\.'/g, "summary: 'The iron silk road connecting Yiwu, Xi’an, and Chongqing to Duisburg, Hamburg, Warsaw, and Madrid. 50% faster than sea freight at 60% lower cost than air freight.', summaryAr: 'طريق الحرير الحديدي الذي يربط الصين بأوروبا. أسرع بنسبة 50٪ من الشحن البحري وبتكلفة أقل بنسبة 60٪ من الشحن الجوي.'");

  // Add Arabic to INSPECTION_SERVICES
  data = data.replace(/name: 'Pre-Shipment Inspection \(PSI\)'/, "name: 'Pre-Shipment Inspection (PSI)', nameAr: 'فحص ما قبل الشحن (PSI)'");
  data = data.replace(/stage: '100% produced, min 80% packaged'/, "stage: '100% produced, min 80% packaged', stageAr: 'إنتاج 100%، تعبئة 80% كحد أدنى'");
  data = data.replace(/description: 'The industry-standard final verification\. Inspectors randomly pull sample cartons per ISO 2859-1 \(AQL Level II\), checking workmanship, packaging integrity, barcode scannability, drop test, weight tolerances, and electrical safety\.'/g, "description: 'The industry-standard final verification. Inspectors randomly pull sample cartons per ISO 2859-1 (AQL Level II), checking workmanship, packaging integrity, barcode scannability, drop test, weight tolerances, and electrical safety.', descriptionAr: 'التحقق النهائي القياسي في الصناعة. يقوم المفتشون بسحب عينات عشوائية وفقاً لمعيار ISO 2859-1 للتحقق من الجودة والتعبئة والسلامة.'");
  data = data.replace(/deliverable: 'Comprehensive 40\+ page photographic report with pass\/fail conclusion within 18 hours\.'/g, "deliverable: 'Comprehensive 40+ page photographic report with pass/fail conclusion within 18 hours.', deliverableAr: 'تقرير فوتوغرافي شامل يتجاوز 40 صفحة مع نتيجة النجاح/الفشل خلال 18 ساعة.'");
  data = data.replace(/turnaround: 'Report delivered within 18 hours of on-site inspection\.'/g, "turnaround: 'Report delivered within 18 hours of on-site inspection.', turnaroundAr: 'يتم تسليم التقرير خلال 18 ساعة من الفحص الميداني.'");
  data = data.replace(/idealFor: 'Mandatory gate check before final balance payment to factory\.'/g, "idealFor: 'Mandatory gate check before final balance payment to factory.', idealForAr: 'فحص إلزامي قبل دفع الرصيد النهائي للمصنع.'");

  data = data.replace(/name: 'During Production Check \(DUPRO\)'/, "name: 'During Production Check (DUPRO)', nameAr: 'فحص أثناء الإنتاج (DUPRO)'");
  data = data.replace(/stage: '20% to 50% completed batch'/, "stage: '20% to 50% completed batch', stageAr: '20% إلى 50% من الدفعة مكتملة'");
  data = data.replace(/description: 'Conducted directly on the production line when the first commercial units emerge\. Catches batch-wide defects, assembly errors, and color deviations early so factory re-tooling happens before total volume is affected\.'/g, "description: 'Conducted directly on the production line when the first commercial units emerge. Catches batch-wide defects, assembly errors, and color deviations early so factory re-tooling happens before total volume is affected.', descriptionAr: 'يتم إجراؤه مباشرة على خط الإنتاج. يكتشف العيوب المبكرة ليتسنى للمصنع إجراء التعديلات قبل تأثر الحجم الإجمالي.'");
  data = data.replace(/deliverable: 'Line audit log, defect photos, speed-to-completion verification\.'/g, "deliverable: 'Line audit log, defect photos, speed-to-completion verification.', deliverableAr: 'سجل تدقيق الخط، صور العيوب، التحقق من سرعة الإنجاز.'");
  data = data.replace(/turnaround: 'Same-day preliminary summary \+ next morning official report\.'/g, "turnaround: 'Same-day preliminary summary + next morning official report.', turnaroundAr: 'ملخص أولي في نفس اليوم + تقرير رسمي في صباح اليوم التالي.'");
  data = data.replace(/idealFor: 'First orders with a new supplier or high-complexity technical goods\.'/g, "idealFor: 'First orders with a new supplier or high-complexity technical goods.', idealForAr: 'الطلبات الأولى مع مورد جديد أو السلع التقنية العالية التعقيد.'");

  data = data.replace(/name: 'Container Loading Supervision \(CLS\)'/, "name: 'Container Loading Supervision (CLS)', nameAr: 'الإشراف على تحميل الحاويات (CLS)'");
  data = data.replace(/stage: 'At factory or consolidation warehouse dock'/, "stage: 'At factory or consolidation warehouse dock', stageAr: 'في رصيف المصنع أو مستودع التجميع'");
  data = data.replace(/description: 'Our inspector oversees physical container stuffing\. We check container seal integrity, floor moisture, weatherproofing, carton stack stability, and ensure the precise bill of lading quantities are loaded into the container without carton crushing\.'/g, "description: 'Our inspector oversees physical container stuffing. We check container seal integrity, floor moisture, weatherproofing, carton stack stability, and ensure the precise bill of lading quantities are loaded into the container without carton crushing.', descriptionAr: 'يشرف مفتشنا على تعبئة الحاوية. نتحقق من سلامة الختم، الرطوبة، استقرار التكديس، ونضمن تحميل الكميات الدقيقة دون تلف.'");
  data = data.replace(/deliverable: 'Photo log of every pallet layer, official Customs seal number record\.'/g, "deliverable: 'Photo log of every pallet layer, official Customs seal number record.', deliverableAr: 'سجل صور لكل طبقة منصة، سجل رقم الختم الجمركي الرسمي.'");
  data = data.replace(/turnaround: 'Real-time WhatsApp photos \+ formal certificate in 12 hours\.'/g, "turnaround: 'Real-time WhatsApp photos + formal certificate in 12 hours.', turnaroundAr: 'صور فورية عبر واتساب + شهادة رسمية خلال 12 ساعة.'");
  data = data.replace(/idealFor: 'High-value goods, fragile items, or multi-factory consolidated shipments\.'/g, "idealFor: 'High-value goods, fragile items, or multi-factory consolidated shipments.', idealForAr: 'السلع عالية القيمة، العناصر الهشة، أو الشحنات المجمعة من مصانع متعددة.'");

  data = data.replace(/name: 'Factory Supplier Audit \(ISO \/ Social\)'/, "name: 'Factory Supplier Audit (ISO / Social)', nameAr: 'تدقيق الموردين والمصانع (FSA)'");
  data = data.replace(/stage: 'Pre-contract \/ Supplier qualification'/, "stage: 'Pre-contract / Supplier qualification', stageAr: 'ما قبل العقد / تأهيل المورد'");
  data = data.replace(/description: 'In-person verification of manufacturing premises in China\. We audit business license authenticity, registered capital, machinery inventory, production capacity, in-house QA laboratories, and legitimate export history to weed out middlemen or fly-by-night brokers\.'/g, "description: 'In-person verification of manufacturing premises in China. We audit business license authenticity, registered capital, machinery inventory, production capacity, in-house QA laboratories, and legitimate export history to weed out middlemen or fly-by-night brokers.', descriptionAr: 'التحقق الميداني من مباني التصنيع. ندقق في أصالة الترخيص التجاري، رأس المال، الآلات، وقدرة الإنتاج لاستبعاد الوسطاء.'");
  data = data.replace(/deliverable: 'Supplier capability scorecard, risk matrix, legal entity verification certificate\.'/g, "deliverable: 'Supplier capability scorecard, risk matrix, legal entity verification certificate.', deliverableAr: 'بطاقة تقييم قدرات المورد، مصفوفة المخاطر، شهادة التحقق من الكيان القانوني.'");
  data = data.replace(/turnaround: '24 hours after plant visit\.'/g, "turnaround: '24 hours after plant visit.', turnaroundAr: '24 ساعة بعد زيارة المصنع.'");
  data = data.replace(/idealFor: 'Vetting prospective Alibaba, Made-in-China, or Canton Fair suppliers\.'/g, "idealFor: 'Vetting prospective Alibaba, Made-in-China, or Canton Fair suppliers.', idealForAr: 'فحص الموردين المحتملين من مواقع مثل علي بابا أو معرض كانتون.'");

  // Add Arabic to SOURCING_STEPS
  data = data.replace(/title: 'Supplier Identification & Screening'/, "title: 'Supplier Identification & Screening', titleAr: 'تحديد الموردين وفحصهم'");
  data = data.replace(/description: 'We query our proprietary database of 4,800\+ audited manufacturers across Guangdong, Zhejiang, and Jiangsu, filtering out trading companies and identifying direct OEM\/ODM factory owners\.'/g, "description: 'We query our proprietary database of 4,800+ audited manufacturers across Guangdong, Zhejiang, and Jiangsu, filtering out trading companies and identifying direct OEM/ODM factory owners.', descriptionAr: 'نبحث في قاعدة بياناتنا التي تضم أكثر من 4800 مصنع مدقق لاستبعاد الشركات التجارية وتحديد أصحاب المصانع المباشرة.'");
  data = data.replace(/title: 'Bilingual Price & MOQ Negotiation'/, "title: 'Bilingual Price & MOQ Negotiation', titleAr: 'التفاوض على الأسعار والكميات بلغتين'");
  data = data.replace(/description: 'Our native Chinese procurement managers negotiate on your behalf using local industrial benchmarks, unlocking true factory domestic rates and reasonable minimum order quantities\.'/g, "description: 'Our native Chinese procurement managers negotiate on your behalf using local industrial benchmarks, unlocking true factory domestic rates and reasonable minimum order quantities.', descriptionAr: 'يتفاوض مدراء المشتريات لدينا بالنيابة عنك باستخدام المعايير المحلية للحصول على الأسعار الحقيقية للمصنع وكميات طلب معقولة.'");
  data = data.replace(/title: 'Sample Collection & Consolidation'/, "title: 'Sample Collection & Consolidation', titleAr: 'جمع العينات وتجميعها'");
  data = data.replace(/description: 'We collect physical prototypes from 3 to 6 competing factories at our Shenzhen or Yiwu warehouse, perform initial bench testing, and consolidate them into a single international express courier box to save 75% on courier fees\.'/g, "description: 'We collect physical prototypes from 3 to 6 competing factories at our Shenzhen or Yiwu warehouse, perform initial bench testing, and consolidate them into a single international express courier box to save 75% on courier fees.', descriptionAr: 'نجمع النماذج الأولية من مصانع متعددة في مستودعاتنا، ونجري اختبارات أولية، ونجمعها في صندوق واحد لتوفير 75٪ من رسوم الشحن السريع.'");
  data = data.replace(/title: 'Chinese Legal Contracts & NNN Protection'/, "title: 'Chinese Legal Contracts & NNN Protection', titleAr: 'العقود القانونية الصينية وحماية NNN'");
  data = data.replace(/description: 'Drafting bilingual Manufacturing Agreements enforceable under PRC jurisdiction in Chinese courts, with non-disclosure, non-use, and non-circumvention \(NNN\) clauses protecting your CAD designs\.'/g, "description: 'Drafting bilingual Manufacturing Agreements enforceable under PRC jurisdiction in Chinese courts, with non-disclosure, non-use, and non-circumvention (NNN) clauses protecting your CAD designs.', descriptionAr: 'صياغة اتفاقيات تصنيع ثنائية اللغة قابلة للتنفيذ بموجب القانون الصيني، مع بنود عدم الإفشاء وعدم الاستخدام وعدم التحايل.'");
  data = data.replace(/title: 'Production Oversight & Milestone Escrow'/, "title: 'Production Oversight & Milestone Escrow', titleAr: 'الإشراف على الإنتاج والدفع المشروط'");
  data = data.replace(/description: 'Active tracking of raw material arrival, tooling timeline, and milestone-based supplier payments tied strictly to independent quality inspection sign-offs\.'/g, "description: 'Active tracking of raw material arrival, tooling timeline, and milestone-based supplier payments tied strictly to independent quality inspection sign-offs.', descriptionAr: 'تتبع نشط لوصول المواد الخام والجدول الزمني، مع مدفوعات للموردين مرتبطة بشكل صارم بموافقات فحص الجودة المستقلة.'");

  // Add Arabic to CORPORATE_COMPARISON
  data = data.replace(/feature: 'Primary Business Role'/, "feature: 'Primary Business Role', featureAr: 'دور العمل الأساسي'");
  data = data.replace(/wfoeChina: 'Full operational presence inside Mainland China\. Can hire local Chinese staff, sign local leases, collect RMB payments, issue official VAT Fapiao, and manage local manufacturing directly\.'/g, "wfoeChina: 'Full operational presence inside Mainland China. Can hire local Chinese staff, sign local leases, collect RMB payments, issue official VAT Fapiao, and manage local manufacturing directly.', wfoeChinaAr: 'وجود تشغيلي كامل داخل البر الرئيسي للصين. يمكن توظيف موظفين محليين، توقيع عقود إيجار، إصدار فواتير ضريبية، وإدارة التصنيع.'");
  data = data.replace(/hkCompany: 'International trading gateway, regional holding company, and global treasury hub\. Perfect for invoicing overseas clients, receiving USD\/EUR\/GBP, and re-invoicing suppliers\.'/g, "hkCompany: 'International trading gateway, regional holding company, and global treasury hub. Perfect for invoicing overseas clients, receiving USD/EUR/GBP, and re-invoicing suppliers.', hkCompanyAr: 'بوابة تجارية دولية، شركة قابضة، ومركز خزانة عالمي. مثالية لفوترة العملاء في الخارج واستلام العملات الأجنبية.'");
  
  data = data.replace(/feature: 'Incorporation Speed'/, "feature: 'Incorporation Speed', featureAr: 'سرعة التأسيس'");
  data = data.replace(/wfoeChina: '3 to 5 weeks \(government name pre-approval, SAMR license, company chおops, tax registration, foreign exchange SAFE setup\)\.'/g, "wfoeChina: '3 to 5 weeks (government name pre-approval, SAMR license, company chおops, tax registration, foreign exchange SAFE setup).', wfoeChinaAr: 'من 3 إلى 5 أسابيع (الموافقات الحكومية، الرخص، الأختام، التسجيل الضريبي).' // fixed spelling on chops");
  data = data.replace(/company chおops/, 'company chops');
  data = data.replace(/hkCompany: '1 to 3 business days \(electronic filing with Hong Kong Companies Registry\)\.'/g, "hkCompany: '1 to 3 business days (electronic filing with Hong Kong Companies Registry).', hkCompanyAr: 'من 1 إلى 3 أيام عمل (إيداع إلكتروني لدى سجل الشركات في هونغ كونغ).'");

  data = data.replace(/feature: 'Corporate Tax Rate'/, "feature: 'Corporate Tax Rate', featureAr: 'معدل ضريبة الشركات'");
  data = data.replace(/wfoeChina: '25% standard corporate income tax \(15% for certified High-Tech Enterprises or Special Economic Zones like Qianhai \/ Hainan Free Trade Port\)\.'/g, "wfoeChina: '25% standard corporate income tax (15% for certified High-Tech Enterprises or Special Economic Zones like Qianhai / Hainan Free Trade Port).', wfoeChinaAr: 'ضريبة دخل شركات قياسية 25٪ (15٪ للشركات التقنية العالية أو المناطق الاقتصادية الخاصة).' ");
  data = data.replace(/hkCompany: 'Two-tier profits tax: 8\.25% on first HKD 2,000,000 profit; 16\.5% thereafter\. 0% tax on offshore-derived income with offshore exemption\.'/g, "hkCompany: 'Two-tier profits tax: 8.25% on first HKD 2,000,000 profit; 16.5% thereafter. 0% tax on offshore-derived income with offshore exemption.', hkCompanyAr: 'نظام ضريبي ذو مستويين: 8.25٪ على أول مليوني دولار هونغ كونغ؛ و16.5٪ بعدها. 0٪ ضريبة على الدخل من الخارج.'");

  data = data.replace(/feature: 'Corporate Banking'/, "feature: 'Corporate Banking', featureAr: 'الخدمات المصرفية للشركات'");
  data = data.replace(/wfoeChina: 'RMB Basic Account \+ USD\/Foreign Currency Capital Account in Mainland China \(Bank of China, ICBC, HSBC China\)\.'/g, "wfoeChina: 'RMB Basic Account + USD/Foreign Currency Capital Account in Mainland China (Bank of China, ICBC, HSBC China).', wfoeChinaAr: 'حساب أساسي باليوان الصيني + حساب رأس مال بالعملات الأجنبية في الصين (بنك الصين، ICBC، HSBC الصين).' ");
  data = data.replace(/hkCompany: 'Multi-currency international business accounts \(HSBC HK, Standard Chartered, Airwallex, Statrys, Currenxie\) with unrestricted global capital movement\.'/g, "hkCompany: 'Multi-currency international business accounts (HSBC HK, Standard Chartered, Airwallex, Statrys, Currenxie) with unrestricted global capital movement.', hkCompanyAr: 'حسابات أعمال دولية متعددة العملات مع حركة رأس مال عالمية غير مقيدة.'");

  data = data.replace(/feature: 'VAT \/ Invoicing \(Fapiao\)'/, "feature: 'VAT / Invoicing (Fapiao)', featureAr: 'ضريبة القيمة المضافة / الفوترة (Fapiao)'");
  data = data.replace(/wfoeChina: 'Can issue official Chinese VAT invoices \(Special 13% or General 6%\/3%\), allowing local Chinese clients to deduct input VAT\.'/g, "wfoeChina: 'Can issue official Chinese VAT invoices (Special 13% or General 6%/3%), allowing local Chinese clients to deduct input VAT.', wfoeChinaAr: 'يمكن إصدار فواتير ضريبية صينية رسمية، مما يتيح للعملاء المحليين خصم الضريبة.' ");
  data = data.replace(/hkCompany: 'Issues international commercial invoices in English\. Cannot issue Chinese domestic VAT Fapiao for Mainland buyers\.'/g, "hkCompany: 'Issues international commercial invoices in English. Cannot issue Chinese domestic VAT Fapiao for Mainland buyers.', hkCompanyAr: 'يصدر فواتير تجارية دولية باللغة الإنجليزية. لا يمكن إصدار الفواتير الضريبية الصينية المحلية للمشترين في البر الرئيسي.'");

  data = data.replace(/feature: 'Physical Presence Requirement'/, "feature: 'Physical Presence Requirement', featureAr: 'متطلبات الوجود المادي'");
  data = data.replace(/wfoeChina: 'Requires a registered commercial lease in China \(we provide compliant virtual registered address in Shenzhen\/Shanghai\)\. Needs Legal Representative\.'/g, "wfoeChina: 'Requires a registered commercial lease in China (we provide compliant virtual registered address in Shenzhen/Shanghai). Needs Legal Representative.', wfoeChinaAr: 'يتطلب عقد إيجار تجاري مسجل في الصين (نوفر عناوين افتراضية متوافقة في شينزين/شانغهاي).' ");
  data = data.replace(/hkCompany: 'No physical office required\. Sino Gate acts as your Designated Company Secretary and Registered Office Address in Hong Kong\.'/g, "hkCompany: 'No physical office required. Sino Gate acts as your Designated Company Secretary and Registered Office Address in Hong Kong.', hkCompanyAr: 'لا يتطلب مكتب مادي. نعمل كأمين سر الشركة وعنوان المكتب المسجل في هونغ كونغ.'");

  fs.writeFileSync('src/data/logisticsData.ts', data);
}

translateLogisticsData();
